FROM node:22-bookworm

RUN apt update && apt upgrade -y && \
    apt-get install -y libnss3\
    libnspr4\
    libdbus-1-3\
    libatk1.0-0\
    libatk-bridge2.0-0\
    libcups2\
    libxcomposite1\
    libxdamage1\
    libxfixes3\
    libxrandr2\
    libgbm1\
    libxkbcommon0\
    libasound2\
    libatspi2.0-0 && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

SHELL ["/bin/bash", "-c"]

RUN npm install -g npm@latest && \
    npm install -g pnpm && \
    pnpm --version

USER node

RUN mkdir -p /home/node/.ssh && \
    ssh-keyscan github.com >> /home/node/.ssh/known_hosts

RUN export SHELL="bash" && pnpm setup

ENV PNPM_HOME="/home/node/.local/share/pnpm"
ENV PATH="${PNPM_HOME}:${PATH}"

RUN SHELL="bash" && \
    pnpm config set store-dir "${PNPM_HOME}/store" && \
    pnpm install -g typescript && \
    pnpm self-update && \
    pnpm --version && tsc --version

RUN pnpx playwright-core install chromium
    
WORKDIR /home/node/workspace

CMD [ "node" ]
