name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write


# set env vars in Github settings here
env:
  SITE_URL: 'https://www.marcandreuf.com'
  PLAUSIBLE_SCRIPT_URL: ''
  PLAUSIBLE_DOMAIN: 'marcandreuf.com'

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: check before
        run: |
          pwd
          ls -la

      - name: build within a container
        run: |
          docker run --rm -t -v .:/home/node/workspace -u node ghcr.io/marcandreuf/base-images/frontend-node22-pnpm-web-dev:main /bin/bash -c "id && ls -la && pnpm install && pnpm build"

      - name: check after
        run: |
          pwd
          ls -la

      # - name: Upload Pages Artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: "./dist/"


  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
